Explicitly require BomRemover in SassNoBomCompressor
The specs all pass, but it fails when used in an app in production mode
with:

    NameError: uninitialized constant AssetBomRemoval::SassNoBomCompressor::BomRemover

Suspect this is because we get rails autoloading for free in test or
development mode, but not so much in production.  Adding an explicit
require gets round this.